"""empty message

Revision ID: 1120974f5175
Revises: 1edcd5b096fc
Create Date: 2022-04-07 16:25:29.091056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1120974f5175'
down_revision = '1edcd5b096fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_post', sa.Column('company_name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_post', 'company_name')
    # ### end Alembic commands ###
