"""empty message

Revision ID: 1edcd5b096fc
Revises: f06c3edad37e
Create Date: 2022-04-07 15:38:36.788009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1edcd5b096fc'
down_revision = 'f06c3edad37e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_post', sa.Column('date', sa.String(), nullable=False))
    op.drop_constraint('company_post_cloudinary_url_key', 'company_post', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('company_post_cloudinary_url_key', 'company_post', ['cloudinary_url'])
    op.drop_column('company_post', 'date')
    # ### end Alembic commands ###
