"""empty message

Revision ID: 43f9690c4386
Revises: 
Create Date: 2022-03-30 13:24:25.531043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43f9690c4386'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('phone_number', sa.String(length=80), nullable=False),
    sa.Column('cloudinary_url', sa.String(length=120), nullable=True),
    sa.Column('company_name', sa.String(length=120), nullable=False),
    sa.Column('adress', sa.String(length=80), nullable=True),
    sa.Column('Instagram_url', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Instagram_url'),
    sa.UniqueConstraint('cloudinary_url'),
    sa.UniqueConstraint('email')
    )
    op.create_table('traveler_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('phone_number', sa.String(length=80), nullable=False),
    sa.Column('cloudinary_url', sa.String(length=120), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('lastname', sa.String(length=80), nullable=True),
    sa.Column('nickname', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cloudinary_url'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nickname')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('traveler_user')
    op.drop_table('company_user')
    # ### end Alembic commands ###
