"""empty message

Revision ID: 6aea36c78a47
Revises: 2f1c0a12d130
Create Date: 2022-04-02 20:22:59.636087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6aea36c78a47'
down_revision = '2f1c0a12d130'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_post', sa.Column('title', sa.String(), nullable=False))
    op.add_column('company_post', sa.Column('description', sa.String(), nullable=True))
    op.alter_column('company_user', 'instagram_url',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.drop_constraint('company_user_cloudinary_url_key', 'company_user', type_='unique')
    op.drop_constraint('traveler_user_cloudinary_url_key', 'traveler_user', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('traveler_user_cloudinary_url_key', 'traveler_user', ['cloudinary_url'])
    op.create_unique_constraint('company_user_cloudinary_url_key', 'company_user', ['cloudinary_url'])
    op.alter_column('company_user', 'instagram_url',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.drop_column('company_post', 'description')
    op.drop_column('company_post', 'title')
    # ### end Alembic commands ###
