"""empty message

Revision ID: 9206b1fc2f6d
Revises: 43f9690c4386
Create Date: 2022-03-30 19:45:08.390297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9206b1fc2f6d'
down_revision = '43f9690c4386'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cloudinary_url', sa.String(length=120), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('state', sa.String(length=120), nullable=False),
    sa.Column('country', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cloudinary_url')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('company_post')
    # ### end Alembic commands ###
