"""empty message

Revision ID: ab4513e4c0d6
Revises: d9eeef254c14
Create Date: 2022-04-07 21:30:40.115682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab4513e4c0d6'
down_revision = 'd9eeef254c14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('company_post_phone_number_key', 'company_post', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('company_post_phone_number_key', 'company_post', ['phone_number'])
    # ### end Alembic commands ###
