"""empty message

Revision ID: f06c3edad37e
Revises: 6aea36c78a47
Create Date: 2022-04-05 14:27:44.963357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f06c3edad37e'
down_revision = '6aea36c78a47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('company_user_instagram_url_key', 'company_user', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('company_user_instagram_url_key', 'company_user', ['instagram_url'])
    # ### end Alembic commands ###
